version: 0.2

env:
  variables:
    ECR_REPO_NAME: "myapp"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      echo Logging in to Amazon ECR...
       ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
       REPOSITORY_URI="$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME"
       aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
       echo Building the Docker image...
       docker build -t $ECR_REPO_NAME .
       docker tag $ECR_REPO_NAME:latest $REPOSITORY_URI:latest
  post_build:
    commands:
       echo Pushing the Docker image to ECR...
       docker push $REPOSITORY_URI:latest
artifacts:
  files:
     '**/*'
