version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-north-1"   # Replace if needed
    ECR_REPO_NAME: "myfirsttestdocket"            # Replace with your ECR repo name
    ACCOUNT_ID: "358521120998"        # Replace with your AWS Account ID
    

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - REPOSITORY_URI="$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "Listing source directory contents:"
      - ls -la
      - echo Repo URI is= $REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $ECR_REPO_NAME .

  post_build:
    commands:
      - echo Tagging image...
      - docker tag $ECR_REPO_NAME:latest $REPOSITORY_URI:latest
      - echo Pushing image...
      - docker push $REPOSITORY_URI:latest

artifacts:
  files: []
